-- ============================================================
-- SEED DATA: 10 Case Studies + 10 Explorations
-- ============================================================

-- Case Studies (10)
INSERT OR IGNORE INTO case_studies (slug, category, reading_time, title, desc, hero_image, logo, live_url, company, design_stack, industry, year, sections, content, is_highlighted) VALUES
('door-v3-enterprise-hrmis', 'Enterprise Dashboard', '12 min read', 'DOOR V3 – Enterprise HRMIS Platform Redesign', 'End-to-end redesign of a complex HRMIS platform serving 200,000+ government employees across Indonesia, focusing on usability and performance at scale.', '/images/work/thumbnail-door.webp', '/images/client_logo/clientlogo_door.svg', 'https://door.id', 'PT Neuronworks Indonesia', '[{"name":"Figma","icon":"devicon:figma","color":"#A259FF"},{"name":"React","icon":"devicon:react","color":"#61DAFB"},{"name":"Tailwind","icon":"devicon:tailwindcss","color":"#38BDF8"}]', '["HRMIS","B2B SaaS","Enterprise"]', '2025', '[{"id":"the-challenge","title":"The Challenge"},{"id":"research-discovery","title":"Research & Discovery"},{"id":"design-system","title":"Design System Architecture"},{"id":"final-outcome","title":"Final Outcome"}]', '<h2 id="the-challenge">The Challenge</h2><p>PT Neuronworks Indonesia needed a complete overhaul of their flagship HRMIS product DOOR. The existing v2 interface was built on legacy technology with poor mobile support, confusing navigation patterns, and accessibility issues that affected 200,000+ daily users.</p><h2 id="research-discovery">Research & Discovery</h2><p>We conducted 40+ stakeholder interviews, analyzed 10,000+ support tickets, and ran usability tests with 60 government employees across 5 different offices. Key findings revealed that 68% of users accessed the system via mobile devices during field visits.</p><h2 id="design-system">Design System Architecture</h2><p>Built a comprehensive design system with 200+ components, tokenized theming for light/dark modes, and WCAG 2.1 AA compliance. Every component was tested across 4 breakpoints and 3 input methods (mouse, keyboard, touch).</p><h2 id="final-outcome">Final Outcome</h2><p>The redesign reduced task completion time by 40%, decreased support tickets by 55%, and received a 92% satisfaction score from users in the pilot rollout.</p>', 1),

('tappp-digital-payment', 'Fintech Dashboard', '10 min read', 'TAPPP – Digital Payment Gateway Experience', 'Designing a frictionless payment dashboard for a leading digital wallet platform in Indonesia, serving both merchants and consumers with real-time transaction analytics.', '/images/work/doormockup-01.webp', '/images/client_logo/clientlogo_tappp.webp', 'https://tappp.id', 'PT TAPPP Teknologi', '[{"name":"Figma","icon":"devicon:figma","color":"#A259FF"},{"name":"Vue","icon":"devicon:vuejs","color":"#42B883"},{"name":"Storybook","icon":"devicon:storybook","color":"#FF4785"}]', '["Fintech","Digital Payment","B2C"]', '2024', '[{"id":"overview","title":"Project Overview"},{"id":"merchant-experience","title":"Merchant Experience"},{"id":"consumer-flow","title":"Consumer Flow"}]', '<h2 id="overview">Project Overview</h2><p>TAPPP is one of Indonesia''s fastest-growing digital wallet platforms. They needed a complete UX overhaul of their merchant dashboard and consumer payment flows to support their expansion from 2M to 10M users.</p><h2 id="merchant-experience">Merchant Experience</h2><p>Designed a real-time analytics dashboard with transaction monitoring, settlement reports, and QR code generation. Implemented progressive disclosure patterns to handle complex financial data without overwhelming users.</p><h2 id="consumer-flow">Consumer Flow</h2><p>Redesigned the payment flow reducing steps from 7 to 3, implementing biometric authentication and smart default selections based on user behavior patterns.</p>', 1),

('pertamina-petroleum-analytics', 'Enterprise Dashboard', '15 min read', 'Pertamina – Petroleum Distribution Analytics', 'Interactive analytics platform for monitoring petroleum distribution across 5,000+ gas stations in Indonesia with real-time supply chain visualization.', '/images/work/thumbnail-door.webp', '/images/client_logo/clientlogo_pertamina.webp', NULL, 'PT Pertamina (Persero)', '[{"name":"Figma","icon":"devicon:figma","color":"#A259FF"},{"name":"D3.js","icon":"devicon:d3js","color":"#F9A03C"},{"name":"Next.js","icon":"devicon:nextjs","color":"#000000"}]', '["Oil & Gas","Supply Chain","Enterprise"]', '2025', '[{"id":"context","title":"Context & Scale"},{"id":"visualization","title":"Data Visualization"},{"id":"impact","title":"Business Impact"}]', '<h2 id="context">Context & Scale</h2><p>Pertamina manages the distribution of petroleum products to over 5,000 gas stations across the Indonesian archipelago. The existing monitoring system relied on legacy dashboards with limited real-time capabilities.</p><h2 id="visualization">Data Visualization</h2><p>Created interactive flow maps showing petroleum movement from refineries to terminals to gas stations. Implemented anomaly detection alerts and predictive supply forecasting using historical data patterns.</p><h2 id="impact">Business Impact</h2><p>The new platform reduced supply chain disruptions by 35% and improved logistics planning efficiency by 50% in the first quarter of deployment.</p>', 1),

('telkom-digital-transformation', 'Enterprise Portal', '11 min read', 'Telkom Indonesia – Digital Service Platform', 'Unified digital service portal for Indonesia''s largest telecommunications provider, consolidating 12 separate customer services into one intuitive platform.', '/images/work/doormockup-01.webp', '/images/client_logo/clientlogo_telkomindonesia.webp', NULL, 'PT Telkom Indonesia', '[{"name":"Figma","icon":"devicon:figma","color":"#A259FF"},{"name":"Angular","icon":"devicon:angularjs","color":"#E23237"},{"name":"Sass","icon":"devicon:sass","color":"#CC6699"}]', '["Telecommunications","Enterprise","B2C"]', '2024', '[{"id":"problem","title":"The Problem"},{"id":"solution","title":"Our Solution"},{"id":"results","title":"Results"}]', '<h2 id="problem">The Problem</h2><p>Telkom Indonesia customers had to navigate through 12 different portals for various services—from bill payments to internet packages to enterprise solutions. This fragmented experience led to high churn rates and overwhelmed customer service teams.</p><h2 id="solution">Our Solution</h2><p>Designed a unified platform using a modular architecture that allowed users to access all Telkom services through a single sign-on. Implemented AI-powered recommendations for personalized service bundles.</p><h2 id="results">Results</h2><p>Customer satisfaction scores improved by 45%, service activation time reduced from 7 days to under 24 hours, and inbound support calls decreased by 30%.</p>', 0),

('amigos-ecommerce-platform', 'E-Commerce Platform', '8 min read', 'Amigos – Social Commerce Redesign', 'Revamping a social commerce platform connecting local Indonesian artisans with global buyers through storytelling-driven product pages.', '/images/work/thumbnail-door.webp', '/images/client_logo/clientlogo_amigos.webp', NULL, 'Amigos Indonesia', '[{"name":"Figma","icon":"devicon:figma","color":"#A259FF"},{"name":"Next.js","icon":"devicon:nextjs","color":"#000000"},{"name":"Shopify","icon":"devicon:shopify","color":"#7AB55C"}]', '["E-Commerce","Social Commerce","B2B2C"]', '2024', '[{"id":"brief","title":"Project Brief"},{"id":"storytelling","title":"Storytelling Design"},{"id":"outcome","title":"Outcome"}]', '<h2 id="brief">Project Brief</h2><p>Amigos connects Indonesian artisans—from batik makers in Solo to silver craftsmen in Bali—with international buyers. The existing platform felt transactional and failed to convey the rich cultural stories behind each product.</p><h2 id="storytelling">Storytelling Design</h2><p>Introduced immersive product pages with artisan profiles, making-of documentaries, and interactive cultural context sections. Each product became a story, not just an item in a catalog.</p><h2 id="outcome">Outcome</h2><p>Average order value increased by 65%, artisan onboarding grew by 200%, and international customer retention improved by 40% year-over-year.</p>', 0),

('mtlab-scientific-dashboard', 'SaaS Dashboard', '9 min read', 'MT Lab – Scientific Research Management', 'Laboratory information management system (LIMS) redesign for one of Southeast Asia''s largest material testing laboratories.', '/images/work/doormockup-01.webp', '/images/client_logo/clientlogo_mtlab.webp', NULL, 'MT Lab Indonesia', '[{"name":"Figma","icon":"devicon:figma","color":"#A259FF"},{"name":"React","icon":"devicon:react","color":"#61DAFB"},{"name":"Python","icon":"devicon:python","color":"#3776AB"}]', '["Laboratory","SaaS","B2B"]', '2025', '[{"id":"background","title":"Background"},{"id":"workflow","title":"Workflow Optimization"},{"id":"compliance","title":"Compliance & Standards"}]', '<h2 id="background">Background</h2><p>MT Lab processes over 50,000 material tests annually for construction, manufacturing, and government clients. Their existing LIMS was built in 2010 and suffered from severe usability debt.</p><h2 id="workflow">Workflow Optimization</h2><p>Mapped and redesigned 15 core laboratory workflows. Reduced steps per test from an average of 23 to 12, automated data entry with IoT sensor integration, and introduced barcode-based sample tracking.</p><h2 id="compliance">Compliance & Standards</h2><p>Built in compliance tracking for ISO/IEC 17025 standards with automated audit trail generation and calibration scheduling. Zero compliance violations in the first 6 months post-launch.</p>', 0),

('oneev-ev-charging', 'Mobile App', '7 min read', 'OneEV – Electric Vehicle Charging Network', 'Mobile app design for Indonesia''s pioneering EV charging network, making electric vehicle ownership accessible and convenient across Java and Bali.', '/images/work/thumbnail-door.webp', '/images/client_logo/clientlogo_oneev.webp', NULL, 'OneEV Indonesia', '[{"name":"Figma","icon":"devicon:figma","color":"#A259FF"},{"name":"Flutter","icon":"devicon:flutter","color":"#02569B"},{"name":"Firebase","icon":"devicon:firebase","color":"#FFCA28"}]', '["GreenTech","Mobility","Mobile App"]', '2025', '[{"id":"vision","title":"Product Vision"},{"id":"features","title":"Key Features"},{"id":"growth","title":"Growth Metrics"}]', '<h2 id="vision">Product Vision</h2><p>OneEV is building Indonesia''s first nationwide EV charging network. They needed a consumer app that would make finding, booking, and paying for charging as simple as getting gasoline—but more delightful.</p><h2 id="features">Key Features</h2><p>Real-time charging station availability map, route planning with range estimation, seamless payment integration with 5 e-wallet providers, and community features for trip sharing and reviews.</p><h2 id="growth">Growth Metrics</h2><p>App achieved 50,000 downloads in the first month, 85% user retention after 90 days, and contributed to a 150% increase in charging sessions quarter-over-quarter.</p>', 0),

('nextiva-voip-platform', 'SaaS Platform', '13 min read', 'Nextiva – Unified Communications Platform', 'Comprehensive redesign of a VoIP and unified communications platform serving 100,000+ business customers across North America.', '/images/work/doormockup-01.webp', '/images/client_logo/clientlogo_nextiva.webp', 'https://nextiva.com', 'Nextiva Inc.', '[{"name":"Figma","icon":"devicon:figma","color":"#A259FF"},{"name":"React","icon":"devicon:react","color":"#61DAFB"},{"name":"Node.js","icon":"devicon:nodejs","color":"#339933"}]', '["Telecommunications","VoIP","SaaS","B2B"]', '2024', '[{"id":"scope","title":"Project Scope"},{"id":"architecture","title":"Information Architecture"},{"id":"metrics","title":"Success Metrics"}]', '<h2 id="scope">Project Scope</h2><p>Nextiva''s platform had grown organically over 15 years through acquisitions, resulting in 5 different admin interfaces with inconsistent UX patterns. The goal was to unify everything into a single cohesive experience.</p><h2 id="architecture">Information Architecture</h2><p>Completely restructured the navigation and information hierarchy through card sorting exercises with 200+ users. Reduced the IA depth from 5 levels to 2, making 95% of tasks accessible within 2 clicks.</p><h2 id="metrics">Success Metrics</h2><p>Admin task completion improved by 60%, new user onboarding time reduced from 2 weeks to 3 days, and NPS score increased from 32 to 68.</p>', 0),

('kangamoon-freelance-platform', 'Web Platform', '8 min read', 'KangaMoon – Freelance Marketplace', 'Designing a unique freelance marketplace focused on creative professionals with built-in portfolio showcase tools and escrow payment protection.', '/images/work/thumbnail-door.webp', '/images/client_logo/clientlogo_kangamoon.webp', NULL, 'KangaMoon Creative', '[{"name":"Figma","icon":"devicon:figma","color":"#A259FF"},{"name":"Laravel","icon":"devicon:laravel","color":"#FF2D20"},{"name":"Alpine.js","icon":"devicon:alpinejs","color":"#8BC0D0"}]', '["Freelance","Marketplace","Creative"]', '2025', '[{"id":"market-gap","title":"Market Gap Analysis"},{"id":"design","title":"Platform Design"},{"id":"launch","title":"Launch Results"}]', '<h2 id="market-gap">Market Gap Analysis</h2><p>Existing freelance platforms like Upwork and Fiverr focus heavily on price competition, undervaluing creative work. KangaMoon aimed to create a premium marketplace where quality and portfolio matter more than lowest bid.</p><h2 id="design">Platform Design</h2><p>Built an interactive portfolio builder with drag-and-drop case study templates, video introduction features, and client verification badges. Introduced a ''match score'' algorithm that connects freelancers with relevant projects.</p><h2 id="launch">Launch Results</h2><p>Platform launched with 500 vetted freelancers and 200 businesses. Average project value is 3x higher than competing platforms, and freelancer satisfaction scores average 4.8/5.</p>', 0),

('arumaya-property-portal', 'Real Estate Platform', '10 min read', 'Arumaya – Premium Property Portal', 'Luxury real estate platform connecting high-net-worth buyers with exclusive properties through immersive virtual tours and white-glove concierge service.', '/images/work/doormockup-01.webp', '/images/client_logo/clientlogo_arumaya.webp', NULL, 'Arumaya Properties', '[{"name":"Figma","icon":"devicon:figma","color":"#A259FF"},{"name":"Three.js","icon":"devicon:threejs","color":"#000000"},{"name":"Next.js","icon":"devicon:nextjs","color":"#000000"}]', '["Real Estate","Luxury","Web3D"]', '2024', '[{"id":"luxury-reimagined","title":"Luxury Reimagined"},{"id":"virtual-tours","title":"Virtual Tours"},{"id":"concierge","title":"Digital Concierge"}]', '<h2 id="luxury-reimagined">Luxury Reimagined</h2><p>Arumaya represents Indonesia''s most exclusive properties—from cliffside villas in Bali to penthouses in Jakarta. The digital experience needed to match the caliber of their $1M+ listings.</p><h2 id="virtual-tours">Virtual Tours</h2><p>Built WebGL-powered 3D property walkthroughs with realistic lighting, material rendering, and interactive hotspots for property details. Users can explore every room as if physically present.</p><h2 id="concierge">Digital Concierge</h2><p>Integrated a white-glove scheduling system for private viewings, legal document preparation, and financing consultation—all accessible through a personalized client portal.</p>', 0);

-- Explorations (10)
INSERT OR IGNORE INTO explorations (title, category, description, image, aspect_ratio, keywords, is_highlighted) VALUES
('AI Prompt Flow Canvas', 'Experimental UI', 'An experimental interface for visualizing and chaining AI prompts into complex workflows, inspired by node-based programming tools like Blender and Houdini.', '/images/exploration/community-1.png', '16:9', 'AI, Workflow, Node Editor, Experimental', 1),
('Neobank Dashboard Concept', 'Fintech', 'Dark-mode neobank dashboard design exploring data-rich layouts with glassmorphism cards and animated micro-interactions for balance and transaction monitoring.', '/images/exploration/community-2.png', '16:9', 'Fintech, Dashboard, Dark Mode, Neumorphism', 1),
('Community Hub Redesign', 'Social Platform', 'A warm, inviting community platform redesign emphasizing accessibility and inclusive design patterns with high-contrast modes and screen-reader optimized navigation.', '/images/exploration/community-3.png', '1:1', 'Community, Social, Accessibility, Warm', 1),
('Sustainable Travel Planner', 'GreenTech', 'Carbon-footprint-aware travel planning interface that suggests eco-friendly routes, accommodations, and activities while gamifying sustainable choices.', '/images/exploration/community-4.png', '16:9', 'Travel, Sustainability, Green, Gamification', 1),
('Spatial Music Player', 'Entertainment', 'A spatial audio music player concept exploring 3D sound visualization, gesture-based controls, and immersive album artwork experiences.', '/images/exploration/community-1.png', '9:16', 'Music, 3D, Spatial Audio, Entertainment', 0),
('Health Metrics Hub', 'HealthTech', 'Personal health data aggregation dashboard connecting wearables, lab results, and fitness apps into a unified health timeline with actionable insights.', '/images/exploration/community-2.png', '16:9', 'Health, Dashboard, Wearables, DataViz', 0),
('AR Shopping Experience', 'Retail', 'Augmented reality shopping experience concept allowing users to visualize furniture and decor in their space before purchasing with real-time lighting adaptation.', '/images/exploration/community-3.png', '1:1', 'AR, Shopping, Retail, 3D, E-Commerce', 0),
('Smart City Command Center', 'GovTech', 'A futuristic smart city operations dashboard monitoring traffic, energy consumption, public safety, and environmental sensors in real-time across an urban grid.', '/images/exploration/community-4.png', '16:9', 'Smart City, IoT, Dashboard, GovTech', 0),
('Recipe Discovery App', 'Lifestyle', 'AI-powered recipe discovery app that learns dietary preferences, suggests meals based on available ingredients, and generates step-by-step cooking guides with video.', '/images/exploration/community-1.png', '9:16', 'Food, AI, Personalization, Lifestyle', 0),
('NFT Gallery Portfolio', 'Web3', 'Minimalist NFT gallery and portfolio showcase for digital artists featuring immersive fullscreen viewing, provenance tracking, and social sharing integration.', '/images/exploration/community-2.png', '16:9', 'NFT, Web3, Gallery, Digital Art', 0);